version: "3.9"

services:
  web:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - transactions-data:/tmp/transactions
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=1
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.infrastructure.workers.celery_app worker --loglevel=info
    volumes:
      - .:/app
      - transactions-data:/tmp/transactions
    depends_on:
      - redis
      - db
      - web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_URL=${REDIS_URL}

  flower:
    image: mher/flower
    container_name: flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    environment:
      - CELERY_BROKER_URL=${REDIS_URL}

volumes:
  dev-db-data:
  transactions-data:
